##
## EPITECH PROJECT, 2019
## MUL_my_rpg_2019
## File description:
## Makefile
##

SRC	=	fight_display.c				\
		csfml_functions.c			\
		csfml_text_functions.c		\
		starter_pack/my_strcat.c	\
		starter_pack/my_strcmp.c	\
		starter_pack/my_strlen.c	\
		starter_pack/my_getnbr.c	\
		starter_pack/int_to_char.c	\
		starter_pack/strn_to_word_array.c

BINARY	=	fight

all:
	gcc -o $(BINARY) $(SRC) -lcsfml-graphics -lcsfml-audio -lcsfml-window -lcsfml-system